### ISSUE TITLE
Pointy Catmull-Clark

### ISSUE THREAD

**Issue by talicopanda** [karansher/computer-graphics-meshes#10]
Is this the result what we should be expecting for Catmull-Clark? I feel like my shape is a bit too pointy on the first and second iterations, but I am wondering if that's expected. If not, does anyone know what might be causing this pointy issue?

Original
<img width="576" alt="image" src="https://user-images.githubusercontent.com/36113553/199789542-933d0714-65eb-4c9f-b7c0-645bdf33cb63.png">
Iteration 1
<img width="571" alt="image" src="https://user-images.githubusercontent.com/36113553/199789582-5503d807-5ea1-42b2-8468-c1a9eb576ac4.png">
Iteration 2
<img width="567" alt="image" src="https://user-images.githubusercontent.com/36113553/199789611-877fe938-47f2-4e50-85c9-a1183d66e9db.png">
Iteration 3
<img width="543" alt="image" src="https://user-images.githubusercontent.com/36113553/199789642-92be5940-6c2a-445e-8ef4-6349f83f73fa.png">
Iteration 4
<img width="550" alt="image" src="https://user-images.githubusercontent.com/36113553/199789703-92ec5468-ea54-4f2e-9f1e-ebf1946a7399.png">

**Comment by cyuan17** [comment]
Hi, I think the expected result should be like the bob-subdivision gif. My suggestion for debugging this is first using a simple object like a cube and checking which vertex is at the wrong position.

**Comment by talicopanda** [comment]
Found the issue, I misinterpreted Catmull-Clark as finding the midpoint of edges instead of the average of its adjacent face average values. Thanks.
